# Change these first
owner: ianmyles # Your GitHub username
repo: uptime # Your Github repository name

# Add your sites here
sites:
  - name: Ian Myles
    url: https://www.ianmyles.com
  - name: Cairde
    url: https://www.cairde.ie
  - name: HealthConnect
    url: https://healthconnect.ie/
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com

status-website:
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Site Monitor
  introTitle: "**This site** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: 
  navbar:
    - title: Status
      href: /uptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
